version: '3.8'

services:
    dev:
        container_name: airbank_api_dev
        image: airbank-api-dev:0.0.1
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:dev
        env_file:
            - ".env"
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        depends_on:
            - postgres
        networks:
            - airbank-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped


    postgres:
        container_name: postgres_db
        image: postgres:14.2
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - airbank-network
        depends_on:
            - pgadmin
        env_file:
            - ".env"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            PG_DATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data


    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        ports:
            - "5500:80"
        networks:
            - airbank-network
        env_file:
            - ".env"
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}


    prod:
        container_name: airbank_api_prod
        image: airbank-api-prod:0.0.1
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - 9229:9229
        env_file:
            - .env
        networks:
            - airbank-network
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped

networks:
    airbank-network:
volumes:
    pgdata:
